(()=>{
'use strict';
const style=document.createElement('style');style.textContent=`
#activeTechBtn{margin-left:auto;margin-right:8px}
.active-tech-overlay{position:fixed;inset:0;z-index:5000;background:rgba(2,5,9,.94);backdrop-filter:blur(10px);display:flex;align-items:stretch;justify-content:center;padding:18px}
.active-tech-panel{width:min(1180px,100%);display:flex;flex-direction:column;border:1px solid #26384a;background:#071019;box-shadow:0 24px 80px rgba(0,0,0,.55);border-radius:18px;overflow:hidden}
.active-tech-head{display:flex;align-items:center;gap:14px;padding:14px 18px;border-bottom:1px solid #1d2b38}.active-tech-head h2{margin:0;font-size:20px}.active-tech-head small{color:#7890a7}.active-tech-close{margin-left:auto}.active-tech-body{display:grid;grid-template-columns:1fr 300px;min-height:0;flex:1}.active-tech-map{min-height:560px;background:#0a1118}.active-tech-list{overflow:auto;padding:12px;border-left:1px solid #1d2b38}.active-tech-card{padding:12px;border:1px solid #1d2b38;border-radius:12px;margin-bottom:9px;background:#0a151f}.active-tech-card b{display:block}.active-tech-card small{display:block;color:#7e94a9;margin-top:4px}.active-tech-card.online{border-color:#1f7056}.active-tech-card.idle{border-color:#806522}.tech-status{display:inline-block;margin-top:8px;font-size:9px;padding:4px 7px;border-radius:99px;border:1px solid #31506a}.leaflet-popup-content-wrapper,.leaflet-popup-tip{background:#071019;color:#e8f4ff}.leaflet-popup-content{margin:12px}.tech-popup strong{font-size:14px}.tech-popup small{display:block;color:#8ba1b6;margin-top:4px}.tech-marker{width:16px;height:16px;border-radius:50%;border:3px solid #071019;box-shadow:0 0 0 2px #56e0ff,0 0 16px rgba(86,224,255,.65);background:#56e0ff}.tech-marker.idle{box-shadow:0 0 0 2px #ffc857,0 0 14px rgba(255,200,87,.5);background:#ffc857}.tech-marker.offline{box-shadow:0 0 0 2px #7d8b98;background:#7d8b98}
@media(max-width:800px){.active-tech-body{grid-template-columns:1fr}.active-tech-list{max-height:260px;border-left:0;border-top:1px solid #1d2b38}.active-tech-map{min-height:430px}}
`;document.head.appendChild(style);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let leafletPromise=null,map=null,markers=new Map(),poll=null;
function loadLeaflet(){if(leafletPromise)return leafletPromise;leafletPromise=new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});return leafletPromise}
function markerIcon(status){return L.divIcon({className:'',html:`<div class="tech-marker ${status.toLowerCase()}"></div>`,iconSize:[18,18],iconAnchor:[9,9]})}
async function loadData(){const r=await fetch('/api/web/technician-locations',{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||d.error||'Lokasi gagal dimuat');return d}
function render(d){const list=document.querySelector('#activeTechList');const seen=new Set();(d.locations||[]).forEach(t=>{seen.add(String(t.technician_id));const lat=t.latitude,lng=t.longitude;if(markers.has(String(t.technician_id))){const m=markers.get(String(t.technician_id));m.setLatLng([lat,lng]).setIcon(markerIcon(t.status));m.setPopupContent(`<div class="tech-popup"><strong>${esc(t.name)}</strong><small>NIK ${esc(t.nik)} • STO ${esc(t.sto)}</small><small>${esc(t.status)} • update ${esc(t.age_seconds)} detik lalu</small></div>`)}else{const m=L.marker([lat,lng],{icon:markerIcon(t.status)}).addTo(map);m.bindPopup(`<div class="tech-popup"><strong>${esc(t.name)}</strong><small>NIK ${esc(t.nik)} • STO ${esc(t.sto)}</small><small>${esc(t.status)} • update ${esc(t.age_seconds)} detik lalu</small></div>`);markers.set(String(t.technician_id),m)}});for(const [id,m] of markers){if(!seen.has(id)){map.removeLayer(m);markers.delete(id)}}list.innerHTML='';if(!d.locations?.length){list.innerHTML='<div class="active-tech-card"><b>BELUM ADA LOKASI AKTIF</b><small>Teknisi perlu membuka Mini App dan mengizinkan lokasi.</small></div>';return}d.locations.forEach(t=>{const c=document.createElement('button');c.className='active-tech-card '+t.status.toLowerCase();c.style.cssText='width:100%;text-align:left;color:#e8f4ff;cursor:pointer';c.innerHTML=`<b>${esc(t.name)}</b><small>NIK ${esc(t.nik)} • ${esc(t.sto)}</small><small>${Number(t.latitude).toFixed(6)}, ${Number(t.longitude).toFixed(6)}</small><span class="tech-status">${esc(t.status)} • ${esc(t.age_seconds)}s</span>`;c.onclick=()=>{map.setView([t.latitude,t.longitude],16);markers.get(String(t.technician_id))?.openPopup()};list.appendChild(c)})}
async function open(){await loadLeaflet();const overlay=document.createElement('section');overlay.className='active-tech-overlay';overlay.innerHTML=`<div class="active-tech-panel"><div class="active-tech-head"><div><h2>TEKNISI AKTIF</h2><small>LIVE FIELD LOCATION • LAST HEARTBEAT</small></div><span id="activeTechCount" class="live-badge">LIVE</span><button class="secondary small active-tech-close">TUTUP</button></div><div class="active-tech-body"><div id="activeTechMap" class="active-tech-map"></div><div id="activeTechList" class="active-tech-list"></div></div></div>`;document.body.appendChild(overlay);overlay.querySelector('.active-tech-close').onclick=close;map=L.map('activeTechMap',{zoomControl:true}).setView([-7.2575,112.7521],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);markers.clear();try{const d=await loadData();render(d)}catch(e){overlay.querySelector('#activeTechList').innerHTML=`<div class="active-tech-card"><b>GAGAL MEMUAT</b><small>${esc(e.message)}</small></div>`}poll=setInterval(async()=>{try{render(await loadData())}catch{}},30000);setTimeout(()=>map.invalidateSize(),100)}
function close(){if(poll)clearInterval(poll);poll=null;markers.clear();map?.remove();map=null;document.querySelector('.active-tech-overlay')?.remove()}
function init(){const b=document.createElement('button');b.id='activeTechBtn';b.className='secondary small';b.textContent='TEKNISI AKTIF';b.onclick=()=>open().catch(e=>console.error(e));const top=document.querySelector('.topbar');if(top)top.insertBefore(b,document.querySelector('#logoutBtn'));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
