const $=s=>document.querySelector(s);
const authCard=$('#authCard'),dashboard=$('#dashboard'),linkView=$('#linkView'),loginView=$('#loginView');
function msg(el,text){if(el)el.textContent=text||''}
function showLogin(){linkView.classList.add('hidden');loginView.classList.remove('hidden')}
function showLink(){loginView.classList.add('hidden');linkView.classList.remove('hidden')}
async function json(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.message||d.error||'Request gagal'),{data:d,status:r.status});return d}
function fmt(n){return Number(n||0).toLocaleString('id-ID')}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function mapsUrl(address){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(String(address||''))}
function tickClock(){const d=new Date();const t=d.toLocaleTimeString('id-ID',{hour12:false,timeZone:'Asia/Jakarta'});const el=$('#clock');if(el)el.textContent=t+' WIB';const ft=$('#footerTime');if(ft)ft.textContent=t+' WIB'}
async function requestLink(){const id=$('#telegramId').value.trim();if(!/^\d{5,20}$/.test(id)){msg($('#linkStatus'),'Masukkan Telegram ID yang valid.');return}$('#linkBtn').disabled=true;msg($('#linkStatus'),'Mengirim permintaan ke Telegram...');try{const d=await json('/api/auth/link/request',{method:'POST',body:JSON.stringify({telegram_id:id})});msg($('#linkStatus'),'Permintaan terkirim. Buka Telegram dan tekan tombol konfirmasi dari Kerja-Bot.');pollLink(d.token)}catch(e){msg($('#linkStatus'),e.message)}finally{$('#linkBtn').disabled=false}}
async function pollLink(token){let tries=0;const timer=setInterval(async()=>{tries++;try{const d=await json('/api/auth/link/status?token='+encodeURIComponent(token));if(d.status==='confirmed'){clearInterval(timer);if(d.has_web_account){msg($('#linkStatus'),'Telegram terverifikasi. Silakan masuk menggunakan NIK dan password dari chatbot.');showLogin();$('#nik').value=d.technician?.nik||''}else msg($('#linkStatus'),'Telegram terverifikasi, tetapi akun Website belum dibuat oleh admin. Minta admin menjalankan /webaccount di chatbot.')}else if(d.status==='expired'){clearInterval(timer);msg($('#linkStatus'),'Permintaan kedaluwarsa. Silakan ulangi.')}}catch(e){clearInterval(timer);msg($('#linkStatus'),e.message)}if(tries>=60)clearInterval(timer)},3000)}
async function login(){const nik=$('#nik').value.trim(),password=$('#password').value;if(!nik||!password){msg($('#loginStatus'),'NIK dan password wajib diisi.');return}$('#loginBtn').disabled=true;msg($('#loginStatus'),'AUTHORISING SESSION...');try{const result=await json('/api/auth/login',{method:'POST',body:JSON.stringify({nik,password})});if(!result?.ok||!result?.technician?.name)throw new Error('Login berhasil tetapi data teknisi tidak lengkap. Silakan login ulang.');await loadDashboard()}catch(e){msg($('#loginStatus'),e.message)}finally{$('#loginBtn').disabled=false}}
async function loadDashboard(){try{const me=await json('/api/auth/me');const tech=me?.technician;if(!me?.ok||!tech||!tech.name)throw new Error('Sesi berhasil dibuat tetapi data teknisi tidak tersedia. Silakan login ulang.');authCard.classList.add('hidden');dashboard.classList.remove('hidden');const name=tech.name;$('#welcome').textContent='Halo, '+name;$('#identity').textContent=`NIK ${tech.nik||'-'} • STO ${tech.sto||'-'}`;$('#role').textContent=String(tech.role||'technician').toUpperCase();if($('#footerName'))$('#footerName').textContent=name;
let daily=0,weekly=0,total=0,leaderboard=[];
const isSupervisor=['admin','superadmin'].includes(String(tech.role||'').toLowerCase());
if(isSupervisor){const [d,w,a]=await Promise.all([json('/api/web/dashboard?area=ALL&period=daily'),json('/api/web/dashboard?area=ALL&period=weekly'),json('/api/web/dashboard?area=ALL&period=all')]);daily=Number(d?.summary?.total_close||0);weekly=Number(w?.summary?.total_close||0);total=Number(a?.summary?.total_close||0);leaderboard=Array.isArray(w?.leaderboard)?w.leaderboard:(Array.isArray(d?.leaderboard)?d.leaderboard:[]);renderLeaderboard(leaderboard);loadAreaSuccessMap();}else{const r=await json('/api/web/my-report');daily=Number(r.daily??r.summary?.daily??0);weekly=Number(r.weekly??r.summary?.weekly??0);total=Number(r.total??r.all??(Array.isArray(r.orders)?r.orders.length:0));}
$('#daily').textContent=fmt(daily);$('#weekly').textContent=fmt(weekly);$('#total').textContent=fmt(total);
const o=await json('/api/web/open-orders');const items=[];(o.areas||[]).forEach(a=>(a.orders||[]).forEach(x=>items.push(x)));const open=items.length;$('#openTotal').textContent=fmt(open);$('#openMini').textContent=fmt(open);$('#orderCount').textContent=fmt(open)+' open';$('#feedState').textContent='SYNCED';$('#orders').innerHTML=open?items.slice(0,30).map(x=>{const address=String(x.address||'').trim();return `<article class="order"><b>${esc(x.customer_name||'-')}</b><small>${esc(x.service_number||'-')} • ${esc(x.ticket_id||'MANUAL')}<br>${esc(address||'Alamat tidak tersedia')}</small><a class="map-btn" href="${mapsUrl(address)}" target="_blank" rel="noopener">▣ MAPS</a><span class="tag">OPEN</span></article>`}).join(''):'<p class="muted">TIDAK ADA ORDER OPEN.</p>';tickClock();setInterval(tickClock,1000)}catch(e){authCard.classList.remove('hidden');dashboard.classList.add('hidden');showLogin();msg($('#loginStatus'),e.message)}}
async function logout(){await json('/api/auth/logout',{method:'POST',body:'{}'}).catch(()=>{});location.reload()}
$('#linkBtn').onclick=requestLink;$('#showLogin').onclick=showLogin;$('#showLink').onclick=showLink;$('#loginBtn').onclick=login;$('#logoutBtn').onclick=logout;loadDashboard();
