const $=s=>document.querySelector(s);
const authCard=$('#authCard'),dashboard=$('#dashboard'),linkView=$('#linkView'),loginView=$('#loginView');
function msg(el,text){if(el)el.textContent=text||''}
function showLogin(){if(linkView)linkView.classList.add('hidden');if(loginView)loginView.classList.remove('hidden')}
function showLink(){if(loginView)loginView.classList.add('hidden');if(linkView)linkView.classList.remove('hidden')}
async function json(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(d.message||d.error||'Request gagal'),{data:d,status:r.status});return d}
function fmt(n){return Number(n||0).toLocaleString('id-ID')}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function mapsUrl(address){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(String(address||''))}
function tickClock(){const d=new Date();const t=d.toLocaleTimeString('id-ID',{hour12:false,timeZone:'Asia/Jakarta'});const el=$('#clock');if(el)el.textContent=t+' WIB';const ft=$('#footerTime');if(ft)ft.textContent=t+' WIB'}
async function requestLink(){const input=$('#telegramId');const id=input?input.value.trim():'';if(!/^\d{5,20}$/.test(id)){msg($('#linkStatus'),'Masukkan Telegram ID yang valid.');return}const btn=$('#linkBtn');if(btn)btn.disabled=true;msg($('#linkStatus'),'Mengirim permintaan ke Telegram...');try{const d=await json('/api/auth/link/request',{method:'POST',body:JSON.stringify({telegram_id:id})});msg($('#linkStatus'),'Permintaan terkirim. Buka Telegram dan tekan tombol konfirmasi dari Kerja-Bot.');pollLink(d.token)}catch(e){msg($('#linkStatus'),e.message)}finally{if(btn)btn.disabled=false}}
async function pollLink(token){let tries=0;const timer=setInterval(async()=>{tries++;try{const d=await json('/api/auth/link/status?token='+encodeURIComponent(token));if(d.status==='confirmed'){clearInterval(timer);if(d.has_web_account){msg($('#linkStatus'),'Telegram terverifikasi. Silakan masuk menggunakan NIK dan password dari chatbot.');showLogin();const nik=$('#nik');if(nik)nik.value=d.technician?.nik||''}else msg($('#linkStatus'),'Telegram terverifikasi, tetapi akun Website belum dibuat oleh admin. Minta admin menjalankan /webaccount di chatbot.')}else if(d.status==='expired'){clearInterval(timer);msg($('#linkStatus'),'Permintaan kedaluwarsa. Silakan ulangi.')}}catch(e){clearInterval(timer);msg($('#linkStatus'),e.message)}if(tries>=60)clearInterval(timer)},3000)}

const analyticsState={area:'ALL',period:'daily',payload:null};
function analyticsPeriodLabel(){return analyticsState.period==='daily'?'HARI INI':analyticsState.period==='weekly'?'MINGGU INI':'KESELURUHAN'}
function analyticsAreaLabel(){return analyticsState.area==='MYR'?'MANYAR':analyticsState.area==='JGR'?'JAGIR':'SEMUA'}
function injectAnalyticsStyles(){if($('#web-analytics-style'))return;const s=document.createElement('style');s.id='web-analytics-style';s.textContent=`
.web-analytics-panel{margin-top:12px}.analytics-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;margin:4px 0 14px}.filter-group{display:flex;align-items:center;gap:5px;flex-wrap:wrap}.filter-label{font-size:8px;font-weight:800;letter-spacing:.13em;color:#4e7384;margin-right:4px}.filter-btn{border:1px solid #23495b;background:#07131c;color:#7592a1;padding:7px 10px;font-size:8px;font-weight:800;letter-spacing:.08em;cursor:pointer}.filter-btn:hover{border-color:#4fdcff;color:#c8f5ff}.filter-btn.is-active{background:#4bdcff;border-color:#4bdcff;color:#031018}.kpi-index-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.index-kpi{border:1px solid #173b4b;background:#07131c;padding:12px 12px 10px;min-height:82px;position:relative;overflow:hidden}.index-kpi:after{content:'';position:absolute;right:-18px;bottom:-22px;width:58px;height:58px;border:1px solid #173b4b;transform:rotate(45deg)}.index-kpi small{display:block;color:#507487;font-size:7px;font-weight:800;letter-spacing:.13em;margin-bottom:7px}.index-kpi strong{display:block;color:#e5f7fc;font:700 24px/1 'Barlow Condensed',sans-serif}.index-kpi em{display:block;margin-top:5px;color:#4fdcff;font-size:7px;font-style:normal;letter-spacing:.08em}.index-kpi.close strong{color:#55e1a1}.index-kpi.open strong{color:#ffbf45}.index-kpi.update strong{color:#63ddff}.index-kpi.reject strong{color:#ff6570}.index-kpi.progress strong{color:#dcefff}.trend-box{margin-top:10px;border:1px solid #173b4b;background:#07131c;padding:12px 14px}.trend-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:6px}.trend-head b{font-size:9px;color:#cbe9f2;letter-spacing:.1em}.trend-head span{font-size:8px;color:#4fdcff;font-weight:800}.line-chart{width:100%;height:250px;display:block}.chart-grid{stroke:#173444;stroke-width:1}.chart-axis{fill:#5c7787;font-size:9px;font-family:Inter,sans-serif}.chart-line{fill:none;stroke:#55e1ff;stroke-width:3;stroke-linecap:round;stroke-linejoin:round}.chart-area{fill:#55e1ff;opacity:.08}.chart-dot{fill:#07131c;stroke:#55e1ff;stroke-width:2}.chart-value{fill:#dff7ff;font-size:8px;font-weight:800;font-family:Inter,sans-serif}.leader-filterbar{display:flex;gap:5px;flex-wrap:wrap;margin:-2px 0 12px}.leader-filterbar .filter-label{align-self:center}.leaderboard-note{font-size:7px;color:#466a7b;letter-spacing:.08em;margin-top:7px}.leader-row .leader-score{color:#55e1ff}.leader-row .leader-meta{color:#557789}.web-analytics-panel .panel-head{margin-bottom:8px}@media(max-width:1100px){.kpi-index-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:650px){.kpi-index-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.line-chart{height:210px}}
`;document.head.appendChild(s)}
function filterButtons(kind){const values=kind==='area'?[['ALL','SEMUA'],['MYR','MANYAR'],['JGR','JAGIR']]:[['daily','HARI INI'],['weekly','MINGGU INI'],['all','KESELURUHAN']];return values.map(([v,l])=>`<button type="button" class="filter-btn" data-filter-kind="${kind}" data-filter-value="${v}">${l}</button>`).join('')}
function setupAnalyticsPanel(){injectAnalyticsStyles();const old=$('#ordersPanel');const source=old||document.querySelector('.orders-panel');if(source){source.className='panel web-analytics-panel';source.id='webAnalyticsPanel';source.innerHTML=`<div class="panel-head"><div><span class="panel-kicker">PERFORMANCE INDEX</span><h2>INDEKS KPI</h2></div><span class="live-badge"><i></i> LIVE</span></div><div class="analytics-toolbar"><div class="filter-group"><span class="filter-label">STO</span>${filterButtons('area')}</div><div class="filter-group"><span class="filter-label">PERIODE</span>${filterButtons('period')}</div></div><div class="kpi-index-grid"><article class="index-kpi"><small>TOTAL CLOSE</small><strong id="idxTotal">0</strong><em id="idxCloseMeta">SEMUA</em></article><article class="index-kpi close"><small>CLOSE</small><strong id="idxClose">0</strong><em>SELESAI</em></article><article class="index-kpi open"><small>OPEN</small><strong id="idxOpen">0</strong><em>MENUNGGU AKSI</em></article><article class="index-kpi progress"><small>PROGRESS</small><strong id="idxProgress">0%</strong><em>TINGKAT PENYELESAIAN</em></article><article class="index-kpi update"><small>UPDATE</small><strong id="idxUpdate">0</strong><em>STATUS BERJALAN</em></article><article class="index-kpi reject"><small>MENOLAK</small><strong id="idxReject">0</strong><em>ORDER DITOLAK</em></article></div><div class="trend-box"><div class="trend-head"><b>TREN PROGRESS CLOSE</b><span id="trendCaption">0 CLOSE</span></div><div id="webLineChart"></div></div>`;source.parentNode.insertBefore(source,source.nextSibling)}else{const main=document.querySelector('.main-grid');if(main){const section=document.createElement('section');section.className='panel web-analytics-panel';section.id='webAnalyticsPanel';section.innerHTML='<div class="panel-head"><div><span class="panel-kicker">PERFORMANCE INDEX</span><h2>INDEKS KPI</h2></div></section>';main.after(section)}}
  document.querySelectorAll('[data-filter-kind]').forEach(btn=>btn.addEventListener('click',()=>{const kind=btn.dataset.filterKind,value=btn.dataset.filterValue;if(kind==='area')analyticsState.area=value;else analyticsState.period=value;syncAnalyticsFilters();loadAnalytics();}));
  syncAnalyticsFilters();
}
function syncAnalyticsFilters(){document.querySelectorAll('[data-filter-kind]').forEach(btn=>{const active=btn.dataset.filterKind==='area'?analyticsState.area:analyticsState.period;btn.classList.toggle('is-active',btn.dataset.filterValue===active)});}
function updateIndexKpis(){const p=analyticsState.payload||{},s=p.summary||{},close=Number(s.total_close||0),open=Number(s.total_open??s.open??0),update=Number(s.total_update??s.update??0),reject=Number(s.total_menolak??s.menolak??0),total=Number(s.total_order??s.total??(close+open));const progress=Number(s.progress??(total?close/total*100:0));if($('#idxTotal'))$('#idxTotal').textContent=fmt(total);if($('#idxClose'))$('#idxClose').textContent=fmt(close);if($('#idxOpen'))$('#idxOpen').textContent=fmt(open);if($('#idxProgress'))$('#idxProgress').textContent=progress.toFixed(1).replace('.0','')+'%';if($('#idxUpdate'))$('#idxUpdate').textContent=fmt(update);if($('#idxReject'))$('#idxReject').textContent=fmt(reject);if($('#idxCloseMeta'))$('#idxCloseMeta').textContent=analyticsAreaLabel()+' • '+analyticsPeriodLabel();}
function renderWebLineChart(){const host=$('#webLineChart');if(!host)return;const trend=Array.isArray(analyticsState.payload?.trend)?analyticsState.payload.trend:[];if(!trend.length){host.innerHTML='<div class="muted" style="padding:40px 0;text-align:center">BELUM ADA DATA TREN.</div>';return}const w=900,h=250,pad={l:42,r:18,t:25,b:34},max=Math.max(1,...trend.map(x=>Number(x.total||0)));const x=i=>pad.l+(trend.length===1?0:i*(w-pad.l-pad.r)/(trend.length-1));const y=v=>pad.t+(h-pad.t-pad.b)-(Number(v||0)/max)*(h-pad.t-pad.b);const points=trend.map((it,i)=>[x(i),y(it.total)]);const line=points.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');const area=line+' L '+x(trend.length-1).toFixed(1)+' '+(h-pad.b)+' L '+x(0).toFixed(1)+' '+(h-pad.b)+' Z';const grid=[0,.25,.5,.75,1].map(r=>{const yy=pad.t+(h-pad.t-pad.b)*(1-r);return `<line class="chart-grid" x1="${pad.l}" y1="${yy}" x2="${w-pad.r}" y2="${yy}"/><text class="chart-axis" x="4" y="${yy+3}">${fmt(Math.round(max*r))}</text>`}).join('');const labels=trend.map((it,i)=>`<text class="chart-axis" x="${x(i)}" y="${h-10}" text-anchor="middle">${esc(it.label||String(it.date||'').slice(5))}</text>`).join('');const dots=points.map((pt,i)=>`<circle class="chart-dot" cx="${pt[0]}" cy="${pt[1]}" r="4"/><text class="chart-value" x="${pt[0]}" y="${pt[1]-9}" text-anchor="middle">${fmt(trend[i].total)}</text>`).join('');host.innerHTML=`<svg class="line-chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="Tren close"><g>${grid}</g><path class="chart-area" d="${area}"/><path class="chart-line" d="${line}"/>${dots}${labels}</svg>`;const total=trend.reduce((a,i)=>a+Number(i.total||0),0);if($('#trendCaption'))$('#trendCaption').textContent=fmt(total)+' CLOSE';}
function renderWebLeaderboard(rows){const list=$('#leaderboard');if(!list)return;const data=Array.isArray(rows)?rows:[];const note=list.parentElement?.querySelector('.leaderboard-note');if(!data.length){list.innerHTML='<p class="muted">BELUM ADA DATA LEADERBOARD.</p>';return}list.replaceChildren();data.slice(0,10).forEach((item,index)=>{const row=document.createElement('article');row.className='leader-row';row.innerHTML=`<span class="leader-rank">${String(index+1).padStart(2,'0')}</span><div class="leader-person"><b>${esc(item.name||'-')}</b><small class="leader-meta">${esc(item.nik||'-')} • ${esc(item.area_label||item.sto||analyticsAreaLabel())}</small></div><strong class="leader-score">${fmt(item.total||0)}</strong>`;row.addEventListener('click',()=>openTechnician(item.key||item.nik));list.appendChild(row)});if(note)note.textContent=`FILTER: ${analyticsAreaLabel()} • ${analyticsPeriodLabel()}`}
function ensureLeaderboardFilters(){const panel=document.querySelector('.status-panel');if(!panel)return;if(panel.querySelector('.leader-filterbar'))return;const head=panel.querySelector('.panel-head');if(!head)return;const bar=document.createElement('div');bar.className='leader-filterbar';bar.innerHTML=`<span class="filter-label">STO</span>${filterButtons('area')}<span class="filter-label" style="margin-left:6px">PERIODE</span>${filterButtons('period')}`;head.after(bar);const note=document.createElement('div');note.className='leaderboard-note';panel.appendChild(note);bar.querySelectorAll('[data-filter-kind]').forEach(btn=>btn.addEventListener('click',()=>{const kind=btn.dataset.filterKind,value=btn.dataset.filterValue;if(kind==='area')analyticsState.area=value;else analyticsState.period=value;syncAnalyticsFilters();loadAnalytics();}));}
async function loadAnalytics(){try{const d=await json('/api/web/dashboard?'+new URLSearchParams({area:analyticsState.area,period:analyticsState.period}));analyticsState.payload=d;updateIndexKpis();renderWebLineChart();renderWebLeaderboard(d.leaderboard||[]);syncAnalyticsFilters();}catch(e){console.error('[WEB ANALYTICS]',e);if($('#webLineChart'))$('#webLineChart').innerHTML='<div class="muted" style="padding:40px 0;text-align:center">DATA ANALYTICS GAGAL DIMUAT.</div>';}}

async function login(){const nikEl=$('#nik'),passEl=$('#password');const nik=nikEl?nikEl.value.trim():'';const password=passEl?passEl.value:'';if(!nik||!password){msg($('#loginStatus'),'NIK dan password wajib diisi.');return}const btn=$('#loginBtn');if(btn)btn.disabled=true;msg($('#loginStatus'),'AUTHORISING SESSION...');try{const result=await json('/api/auth/login',{method:'POST',body:JSON.stringify({nik,password})});if(!result?.ok||!result?.technician?.name)throw new Error('Login berhasil tetapi data teknisi tidak lengkap. Silakan login ulang.');await loadDashboard()}catch(e){msg($('#loginStatus'),e.message)}finally{if(btn)btn.disabled=false}}
async function loadDashboard(){try{const me=await json('/api/auth/me');const tech=me?.technician;if(!me?.ok||!tech||!tech.name)throw new Error('Sesi berhasil dibuat tetapi data teknisi tidak tersedia. Silakan login ulang.');if(authCard)authCard.classList.add('hidden');if(dashboard)dashboard.classList.remove('hidden');const name=tech.name;const welcome=$('#welcome'),identity=$('#identity'),role=$('#role');if(welcome)welcome.textContent='Halo, '+name;if(identity)identity.textContent=`NIK ${tech.nik||'-'} • STO ${tech.sto||'-'}`;if(role)role.textContent=String(tech.role||'technician').toUpperCase();const footerName=$('#footerName');if(footerName)footerName.textContent=name;
const isSupervisor=['admin','superadmin'].includes(String(tech.role||'').toLowerCase());
if(isSupervisor){setupAnalyticsPanel();ensureLeaderboardFilters();const [d,w,a]=await Promise.all([json('/api/web/dashboard?area=ALL&period=daily'),json('/api/web/dashboard?area=ALL&period=weekly'),json('/api/web/dashboard?area=ALL&period=all')]);const daily=Number(d?.summary?.total_close||0),weekly=Number(w?.summary?.total_close||0),total=Number(a?.summary?.total_close||0);const dailyEl=$('#daily'),weeklyEl=$('#weekly'),totalEl=$('#total');if(dailyEl)dailyEl.textContent=fmt(daily);if(weeklyEl)weeklyEl.textContent=fmt(weekly);if(totalEl)totalEl.textContent=fmt(total);analyticsState.payload=w;renderWebLeaderboard(w?.leaderboard||[]);await loadAnalytics();if(typeof loadAreaSuccessMap==='function')loadAreaSuccessMap();}
else{const r=await json('/api/web/my-report');const daily=Number(r.daily??r.summary?.daily??0),weekly=Number(r.weekly??r.summary?.weekly??0),total=Number(r.total??r.all??(Array.isArray(r.orders)?r.orders.length:0));const dailyEl=$('#daily'),weeklyEl=$('#weekly'),totalEl=$('#total');if(dailyEl)dailyEl.textContent=fmt(daily);if(weeklyEl)weeklyEl.textContent=fmt(weekly);if(totalEl)totalEl.textContent=fmt(total);}
const o=await json('/api/web/open-orders');const items=[];(o.areas||[]).forEach(a=>(a.orders||[]).forEach(x=>items.push(x)));const open=items.length;const openTotal=$('#openTotal');if(openTotal)openTotal.textContent=fmt(open);tickClock();if(!window.__clockTimer)window.__clockTimer=setInterval(tickClock,1000)}catch(e){if(authCard)authCard.classList.remove('hidden');if(dashboard)dashboard.classList.add('hidden');showLogin();msg($('#loginStatus'),e.message)}}
async function logout(){await json('/api/auth/logout',{method:'POST',body:'{}'}).catch(()=>{});location.reload()}
if($('#linkBtn'))$('#linkBtn').onclick=requestLink;if($('#showLogin'))$('#showLogin').onclick=showLogin;if($('#showLink'))$('#showLink').onclick=showLink;if($('#loginBtn'))$('#loginBtn').onclick=login;if($('#logoutBtn'))$('#logoutBtn').onclick=logout;loadDashboard();
