(()=>{
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function styles(){if(document.getElementById('zoneMapStyles'))return;const s=document.createElement('style');s.id='zoneMapStyles';s.textContent=`#zoneMapStage{position:relative;height:100%;min-height:420px;background:#071018}#zoneMapCanvas{position:absolute;inset:0}.zone-panel{position:absolute;z-index:900;right:14px;top:14px;width:280px;max-height:calc(100% - 28px);overflow:auto;background:rgba(5,10,15,.92);border:1px solid rgba(92,224,255,.25);backdrop-filter:blur(10px);padding:14px}.zone-panel h3{margin:0 0 8px;font:700 20px 'Barlow Condensed',sans-serif;letter-spacing:.08em}.zone-stat{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.08);font-size:12px}.zone-item{padding:10px 0;border-bottom:1px solid rgba(255,255,255,.08);cursor:pointer}.zone-item b{display:block;font-size:13px}.zone-item small{opacity:.65}.customer-dot{width:9px;height:9px;border-radius:50%;background:#5ce0ff;border:2px solid #061018}.zone-label{background:rgba(5,10,15,.85);color:#5ce0ff;border:1px solid rgba(92,224,255,.45);font:700 12px 'Barlow Condensed';padding:3px 6px}.zone-sync{margin-top:10px;width:100%;padding:8px;border:1px solid rgba(92,224,255,.3);background:transparent;color:#5ce0ff;cursor:pointer}.leaflet-popup-content{font-family:Inter,sans-serif;font-size:12px}.leaflet-control-attribution{font-size:9px}`;document.head.appendChild(s)}
async function openZoneMap(){styles();await loadLeaflet();const stage=document.querySelector('.map-stage');if(!stage)return;stage.innerHTML='<div id="zoneMapStage"><div id="zoneMapCanvas"></div><div class="zone-panel"><h3>CUSTOMER ZONES</h3><div class="zone-stat"><span>GEOCODED</span><b id="zg">0</b></div><div class="zone-stat"><span>ZONES</span><b id="zz">0</b></div><div class="zone-stat"><span>CUSTOMERS</span><b id="zc">0</b></div><div id="zoneList"></div><button class="zone-sync" id="zoneSync">SYNC 3 ALAMAT</button></div></div>';
const map=L.map('zoneMapCanvas',{zoomControl:true}).setView([-7.27,112.75],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);const zoneLayer=L.layerGroup().addTo(map),customerLayer=L.layerGroup().addTo(map);
async function refresh(sync=false){const url='/api/web/customer-zones'+(sync?'?sync=1':'');const r=await fetch(url,{credentials:'same-origin'});if(!r.ok)throw new Error('Zone API '+r.status);const d=await r.json();zoneLayer.clearLayers();customerLayer.clearLayers();(d.customers||[]).forEach(c=>{const m=L.circleMarker([c.latitude,c.longitude],{radius:5,weight:2,fillOpacity:.8});m.bindPopup('<b>'+esc(c.customer_name||'-')+'</b><br>'+esc(c.service_number||'-')+'<br>'+esc(c.address||'-')+'<br><b>'+esc(c.zone_id||'-')+'</b>');m.addTo(customerLayer)});(d.zones||[]).forEach(z=>{const m=L.marker([z.latitude,z.longitude],{icon:L.divIcon({className:'zone-label',html:esc(z.label),iconSize:null})});m.bindPopup('<b>'+esc(z.label)+'</b><br>Customer: '+z.total+'<br>Open: '+z.open);m.addTo(zoneLayer)});document.getElementById('zg').textContent=d.geocoded_count||0;document.getElementById('zz').textContent=(d.zones||[]).length;document.getElementById('zc').textContent=(d.customers||[]).length;document.getElementById('zoneList').innerHTML=(d.zones||[]).map(z=>'<div class="zone-item" data-lat="'+z.latitude+'" data-lng="'+z.longitude+'"><b>'+esc(z.label)+'</b><small>'+z.total+' customer • '+z.open+' open</small></div>').join('')||'<p class="muted">Belum ada koordinat customer. Tekan SYNC.</p>';document.querySelectorAll('.zone-item').forEach(el=>el.onclick=()=>map.setView([+el.dataset.lat,+el.dataset.lng],16));if((d.customers||[]).length){const b=L.latLngBounds((d.customers||[]).map(c=>[c.latitude,c.longitude]));map.fitBounds(b,{padding:[30,30],maxZoom:15})}}
document.getElementById('zoneSync').onclick=async()=>{document.getElementById('zoneSync').disabled=true;document.getElementById('zoneSync').textContent='GEOCODING...';try{await refresh(true)}catch(e){console.error(e)}finally{document.getElementById('zoneSync').disabled=false;document.getElementById('zoneSync').textContent='SYNC 3 ALAMAT'}};try{await refresh(false)}catch(e){console.error(e)}window.KerjaBotCustomerZones={refresh};}
window.KerjaBotOpenZoneMap=openZoneMap;
})();
