(()=>{
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const ROMAN=['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX'];
const toRoman=n=>{n=Number(n);return Number.isInteger(n)&&n>=1&&n<=20?ROMAN[n]:String(n)};
function normalizeStreet(address){
 let t=String(address??'').toUpperCase().replace(/[^A-Z0-9/ -]+/g,' ').replace(/\s+/g,' ').trim();if(!t)return '';
 t=t.replace(/\bJLN\.?\b/g,'JL').replace(/\bJALAN\b/g,'JL').replace(/\bGANG\b/g,'GG');
 const p=t.split(' '),nums=[];p.forEach((x,i)=>/^\d+$/.test(x)&&nums.push(i));
 if(nums.length>=2){const house=nums[nums.length-1];for(const i of nums.slice(0,-1))p[i]=toRoman(p[i]);t=p.slice(0,house).join(' ')+' NO '+p[house]}
 else if(nums.length===1){const i=nums[0];if(i>0)t=p.slice(0,i).join(' ')+' NO '+p[i]}
 return t.replace(/\s+/g,' ').trim();
}
function geocodeStreetName(address){return normalizeStreet(address).replace(/\s+NO\s+\d+.*$/i,'').trim()}
const cacheKey=a=>'kerja-bot-geo-street:'+geocodeStreetName(a).toLowerCase().replace(/\s+/g,' ');
let opening=null,queueRunning=false;
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function styles(){if(document.getElementById('zoneMapStyles'))return;const s=document.createElement('style');s.id='zoneMapStyles';s.textContent=`#zoneMapStage{position:relative;height:100%;min-height:420px;background:#071018}#zoneMapCanvas{position:absolute;inset:0}.zone-panel{position:absolute;z-index:900;right:14px;top:14px;width:280px;max-height:calc(100% - 28px);overflow:auto;background:rgba(5,10,15,.92);border:1px solid rgba(92,224,255,.25);backdrop-filter:blur(10px);padding:14px}.zone-panel h3{margin:0 0 8px;font:700 20px 'Barlow Condensed',sans-serif;letter-spacing:.08em}.zone-stat{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.08);font-size:12px}.zone-item{padding:10px 0;border-bottom:1px solid rgba(255,255,255,.08);cursor:pointer}.zone-item b{display:block;font-size:13px}.zone-item small{opacity:.65}.zone-label{background:rgba(5,10,15,.9);color:#5ce0ff;border:1px solid rgba(92,224,255,.45);font:700 12px 'Barlow Condensed';padding:3px 6px}.zone-sync{margin-top:10px;width:100%;padding:8px;border:1px solid rgba(92,224,255,.3);background:transparent;color:#5ce0ff;cursor:pointer}.leaflet-popup-content{font-family:Inter,sans-serif;font-size:12px}.leaflet-control-attribution{font-size:9px}@media(max-width:700px){.zone-panel{left:10px;right:10px;top:10px;width:auto;max-height:180px}.zone-item{display:inline-block;width:48%;vertical-align:top}}`;document.head.appendChild(s)}
function flattenOrders(o){
 const items=[];
 if(Array.isArray(o?.areas))o.areas.forEach(a=>(Array.isArray(a?.orders)?a.orders:[]).forEach(x=>items.push(x)));
 if(!items.length&&Array.isArray(o?.orders))o.orders.forEach(x=>items.push(x));
 return items;
}
async function getOrders(){
 const r=await fetch('/api/web/open-orders',{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw Error('Order API '+r.status);const o=await r.json();return {items:flattenOrders(o),raw:o};
}
function readCache(street){try{const v=JSON.parse(localStorage.getItem(cacheKey(street))||'null');return v&&Number.isFinite(+v.lat)&&Number.isFinite(+v.lng)?v:null}catch{return null}}
async function geocode(address){const street=geocodeStreetName(address),k=cacheKey(street);if(!street)return null;const old=readCache(street);if(old)return old;
 const url='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=id&q='+encodeURIComponent(street+', Surabaya, Jawa Timur, Indonesia');
 try{const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw Error('Nominatim '+r.status);const d=await r.json();if(d&&d[0]){const out={lat:+d[0].lat,lng:+d[0].lon,name:d[0].display_name||'',street};if(Number.isFinite(out.lat)&&Number.isFinite(out.lng)){localStorage.setItem(k,JSON.stringify(out));return out}}}catch(e){console.warn('[CUSTOMER ZONES] geocode failed:',street,e)}return null}
async function openZoneMap(){
 if(opening)return opening;
 opening=(async()=>{styles();await loadLeaflet();const stage=document.querySelector('.map-stage');if(!stage)throw new Error('Map stage tidak tersedia.');
  if(stage.dataset.zoneReady==='1'){const canvas=document.getElementById('zoneMapCanvas');if(canvas&&canvas._leaflet_id)return;stage.dataset.zoneReady='0'}
  stage.innerHTML='<div id="zoneMapStage"><div id="zoneMapCanvas"></div><div class="zone-panel"><h3>CUSTOMER ZONES</h3><div class="zone-stat"><span>OPEN ORDERS</span><b id="zo">0</b></div><div class="zone-stat"><span>GEOCODED STREETS</span><b id="zg">0</b></div><div class="zone-stat"><span>ZONES</span><b id="zz">0</b></div><div class="zone-stat"><span>CUSTOMERS</span><b id="zc">0</b></div><div id="zoneList"></div><button class="zone-sync" id="zoneSync">SYNC ALAMAT</button></div></div>';
  const map=L.map('zoneMapCanvas',{zoomControl:true}).setView([-7.27,112.75],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);const customerLayer=L.layerGroup().addTo(map),zoneLayer=L.layerGroup().addTo(map);stage.dataset.zoneReady='1';
  async function render(){
   const loaded=await getOrders(),orders=loaded.items,groups={},customers=[];const streets=[...new Set(orders.map(o=>normalizeStreet(o?.address||'')).filter(Boolean))];
   const zo=document.getElementById('zo');if(zo)zo.textContent=orders.length;
   for(const o of orders){const address=String(o?.address||'').trim(),street=normalizeStreet(address),g=readCache(street);if(!street||!g)continue;const lat=+g.lat,lng=+g.lng,key=geocodeStreetName(street).toLowerCase().replace(/\s+/g,' ').trim();if(!groups[key])groups[key]={id:'Z'+String(Object.keys(groups).length+1).padStart(2,'0'),street:geocodeStreetName(street),lat,lng,total:0,open:0,close:0,update:0,menolak:0,orders:[]};const z=groups[key];z.total++;z.orders.push(o);const status=String(o?.result||o?.status||'OPEN').trim().toUpperCase();if(status==='OPEN')z.open++;else if(['CLOSE','CLOSED','DONE','SELESAI','COMPLETED'].includes(status))z.close++;else if(['UPDATE','UPDATED','PROGRESS','ON PROGRESS','PENDING'].includes(status)||status.includes('UPDATE'))z.update++;else if(['MENOLAK','REJECT','DITOLAK'].includes(status))z.menolak++;customers.push({...o,latitude:lat,longitude:lng,zone_id:z.id,street})}
   customerLayer.clearLayers();zoneLayer.clearLayers();Object.values(groups).forEach(z=>{const items=z.orders.map((o,i)=>'<div style="padding:9px 0;border-top:1px solid #ddd"><b>'+(i+1)+'. '+esc(o?.customer_name||o?.name||'-')+'</b><br><b>INET:</b> '+esc(o?.service_number||'-')+'<br><b>TIKET:</b> '+esc(o?.ticket_id||'-')+'<br><b>HP:</b> '+esc(o?.customer_phone||o?.phone||'-')+'<br><b>ONT:</b> '+esc(o?.ont_type||'-')+'<br><b>STO:</b> '+esc(o?.sto||'-')+'<br><b>VALINS:</b> '+esc(o?.valins_id||'-')+'<br><b>RESULT:</b> '+esc(o?.result||o?.status||'-')+'<br><b>ALAMAT:</b> '+esc(o?.address||'-')+'</div>').join('');const popup='<div style="min-width:280px;max-width:390px"><div style="font-size:17px;font-weight:800;margin-bottom:4px">'+esc(z.street)+'</div><div style="font-size:13px;margin-bottom:5px"><b>'+z.total+' ORDER</b> · ZONA '+esc(z.id)+'</div><div style="font-size:11px;opacity:.75;margin-bottom:6px">OPEN '+z.open+' · CLOSE '+z.close+' · UPDATE '+z.update+' · MENOLAK '+z.menolak+'</div>'+items+'</div>';L.marker([z.lat,z.lng],{icon:L.divIcon({className:'zone-label',html:'<span style="font-weight:800">'+esc(String(z.total))+' ORDER</span>',iconSize:null})}).bindPopup(popup,{maxWidth:410}).addTo(zoneLayer)});
   customers.forEach(c=>L.circleMarker([c.latitude,c.longitude],{radius:5,weight:2,fillOpacity:.8}).bindPopup('<b>'+esc(c.customer_name||'-')+'</b><br>INET: '+esc(c.service_number||'-')+'<br>TIKET: '+esc(c.ticket_id||'-')+'<br>RESULT: '+esc(c.result||c.status||'-')+'<br>Alamat: '+esc(c.address||'-')+'<br><b>'+esc(c.zone_id)+'</b>').addTo(customerLayer));
   const zg=document.getElementById('zg'),zz=document.getElementById('zz'),zc=document.getElementById('zc'),list=document.getElementById('zoneList');if(!zg||!zz||!zc||!list)return streets;const geocodedStreets=new Set(Object.keys(groups));zg.textContent=geocodedStreets.size;zz.textContent=geocodedStreets.size;zc.textContent=customers.length;list.innerHTML=Object.values(groups).map(z=>'<div class="zone-item" data-lat="'+z.lat+'" data-lng="'+z.lng+'"><b>'+esc(z.street)+'</b><small>'+z.total+' order · OPEN '+z.open+' · CLOSE '+z.close+'</small></div>').join('')||'<p class="muted">'+(orders.length?'Geocoding alamat berjalan otomatis...':'TIDAK ADA ORDER OPEN.')+'</p>';document.querySelectorAll('.zone-item').forEach(el=>el.onclick=()=>map.setView([+el.dataset.lat,+el.dataset.lng],17));if(customers.length){const b=L.latLngBounds(customers.map(c=>[c.latitude,c.longitude]));map.fitBounds(b,{padding:[40,40],maxZoom:15})}
   return streets;
  }
  async function runGeocodeQueue(streets,force=false){if(queueRunning)return;queueRunning=true;try{for(const street of streets){if(readCache(street))continue;await geocode(street);await render();await new Promise(r=>setTimeout(r,1100))}}finally{queueRunning=false}}
  const sync=document.getElementById('zoneSync');if(sync)sync.onclick=async()=>{sync.disabled=true;sync.textContent='GEOCODING...';try{const streets=await render();await runGeocodeQueue(streets,true)}catch(e){console.warn('zone sync',e)}finally{sync.disabled=false;sync.textContent='SYNC ALAMAT'}};
  const streets=await render();runGeocodeQueue(streets,false).catch(console.warn);setInterval(async()=>{if(queueRunning)return;try{const s=await render();runGeocodeQueue(s,false).catch(console.warn)}catch(e){console.warn(e)}},60000);window.KerjaBotCustomerZones={refresh:render,normalizeStreet,geocodeStreetName};
 })();try{return await opening}finally{opening=null}}
window.KerjaBotOpenZoneMap=openZoneMap;
})();
