(()=>{
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const menuItems=[
 ['zones','CUSTOMER ZONES','Peta pelanggan & wilayah kerja'],
 ['techs','TEKNISI AKTIF','Live GPS teknisi'],
 ['orders','ORDERAN','Daftar order & status'],
 ['reports','LAPORAN','Kinerja dan rekap'],
 ['payroll','PAYROLL','Rekap penghasilan'],
 ['profile','PROFIL','Akun dan identitas']
];
function styles(){if($('#menuStyles'))return;const s=document.createElement('style');s.id='menuStyles';s.textContent=`.menu-btn{display:inline-flex;align-items:center;justify-content:center;width:42px;height:42px;margin-right:10px;border:1px solid rgba(92,224,255,.3);background:rgba(5,10,15,.7);color:#5ce0ff;font-size:22px;cursor:pointer}.menu-overlay{position:fixed;inset:0;z-index:5000;background:rgba(2,5,9,.78);backdrop-filter:blur(12px);display:none}.menu-overlay.open{display:block}.menu-drawer{width:min(390px,92vw);height:100%;background:#070d14;border-right:1px solid rgba(92,224,255,.25);padding:24px;box-shadow:20px 0 60px rgba(0,0,0,.45);overflow:auto}.menu-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:28px}.menu-head h2{margin:0;font:700 28px 'Barlow Condensed',sans-serif;letter-spacing:.08em}.menu-close{border:0;background:none;color:#8da2b3;font-size:28px;cursor:pointer}.menu-item{display:block;width:100%;text-align:left;padding:17px 14px;margin:8px 0;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.025);color:#fff;cursor:pointer}.menu-item:hover{border-color:rgba(92,224,255,.4);background:rgba(92,224,255,.06)}.menu-item b{display:block;font:700 19px 'Barlow Condensed',sans-serif;letter-spacing:.07em;color:#5ce0ff}.menu-item small{display:block;margin-top:3px;color:#8395a5}.menu-footer{margin-top:28px;padding-top:18px;border-top:1px solid rgba(255,255,255,.08);color:#637586;font-size:11px}.feature-view{display:none}.feature-view.active{display:block}.feature-view .feature-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:18px}.feature-view h1{margin:0;font:700 clamp(34px,5vw,54px) 'Barlow Condensed',sans-serif;letter-spacing:.03em}.feature-view .feature-kicker{color:#5ce0ff;font-size:11px;letter-spacing:.16em}.feature-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.feature-card{padding:20px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.025)}.feature-card b{display:block;font:700 30px 'Barlow Condensed',sans-serif;color:#5ce0ff}.feature-card span{color:#8395a5;font-size:12px}.back-dashboard{margin-bottom:18px}.profile-row{display:flex;justify-content:space-between;padding:13px 0;border-bottom:1px solid rgba(255,255,255,.07)}.profile-row span{color:#8395a5}.profile-row b{color:#fff}.empty-feature{padding:30px;border:1px dashed rgba(92,224,255,.2);color:#8395a5}.compact-orders{display:grid;gap:10px}.compact-orders .order{position:relative}.feature-view .orders-panel{display:block}.map-feature-stage{height:calc(100vh - 210px);min-height:520px}.map-feature-stage .map-stage{height:100%}@media(max-width:700px){.feature-grid{grid-template-columns:1fr}.feature-view .feature-head{align-items:start;gap:12px;flex-direction:column}}`;document.head.appendChild(s)}
function shell(){const d=$('#dashboard');if(!d||$('#menuOverlay'))return;styles();const top=d.querySelector('.topbar');if(top){const btn=document.createElement('button');btn.className='menu-btn';btn.id='hamburgerBtn';btn.setAttribute('aria-label','Menu');btn.textContent='☰';top.insertBefore(btn,top.firstChild);}
const ov=document.createElement('div');ov.id='menuOverlay';ov.className='menu-overlay';ov.innerHTML=`<aside class="menu-drawer"><div class="menu-head"><h2>KERJA-BOT MENU</h2><button class="menu-close" id="menuClose">×</button></div><div>${menuItems.map(x=>`<button class="menu-item" data-view="${x[0]}"><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div><div class="menu-footer">FIELD COMMAND / SECURE SESSION</div></aside>`;document.body.appendChild(ov);$('#hamburgerBtn').onclick=()=>ov.classList.add('open');$('#menuClose').onclick=()=>ov.classList.remove('open');ov.addEventListener('click',e=>{if(e.target===ov)ov.classList.remove('open');});
const main=d.querySelector('.command-strip');const hero=d.querySelector('.hero');const kpi=d.querySelector('.kpi-grid');const grid=d.querySelector('.main-grid');const orders=d.querySelector('.orders-panel');const footer=d.querySelector('.dashboard-footer');const host=document.createElement('div');host.id='featureHost';host.className='feature-host';footer.parentNode.insertBefore(host,footer);
const views={zones:'CUSTOMER ZONES',techs:'TEKNISI AKTIF',orders:'ORDERAN',reports:'LAPORAN',payroll:'PAYROLL',profile:'PROFIL'};Object.entries(views).forEach(([id,title])=>{const v=document.createElement('section');v.id='view-'+id;v.className='feature-view';v.innerHTML=`<button class="secondary small back-dashboard">← DASHBOARD</button><div class="feature-head"><div><span class="feature-kicker">FIELD COMMAND / ${title}</span><h1>${title}</h1></div></div><div id="content-${id}"></div>`;host.appendChild(v);});
function closeMenu(){ov.classList.remove('open')}
function showDashboard(){host.querySelectorAll('.feature-view').forEach(v=>v.classList.remove('active'));[main,hero,kpi,grid,orders].forEach(x=>x&&(x.style.display=''));closeMenu();}
function show(id){[main,hero,kpi,grid,orders].forEach(x=>x&&(x.style.display='none'));host.querySelectorAll('.feature-view').forEach(v=>v.classList.remove('active'));$('#view-'+id).classList.add('active');closeMenu();loadView(id)}
host.querySelectorAll('.back-dashboard').forEach(b=>b.onclick=showDashboard);ov.querySelectorAll('.menu-item').forEach(b=>b.onclick=()=>{const id=b.dataset.view;if(id==='techs'){closeMenu();const x=$('#activeTechBtn');if(x)x.click();else window.KerjaBotOpenActiveTechnicians?.()}else show(id)});
async function loadView(id){const c=$('#content-'+id);if(!c||c.dataset.loaded==='1')return;c.dataset.loaded='1';if(id==='zones'){c.innerHTML='<div class="map-feature-stage"><div class="map-stage"></div></div>';const old=document.querySelector('.map-panel .map-stage');const stage=c.querySelector('.map-stage');if(window.KerjaBotOpenZoneMap){const temp=document.createElement('div');temp.className='map-stage';stage.replaceWith(temp);const original=document.querySelector('.map-stage');window.KerjaBotOpenZoneMap();const generated=document.querySelector('.map-stage');if(generated&&generated!==temp){temp.replaceWith(generated)}}else c.innerHTML='<div class="empty-feature">Customer Zones belum tersedia.</div>';return}
if(id==='orders'){try{const o=await fetch('/api/web/open-orders',{credentials:'same-origin'}).then(r=>r.json());const items=[];(o.areas||[]).forEach(a=>(a.orders||[]).forEach(x=>items.push(x)));c.innerHTML=`<div class="feature-card"><span>OPEN QUEUE</span><b>${items.length.toLocaleString('id-ID')}</b></div><div class="compact-orders" style="margin-top:14px">${items.map(x=>`<article class="order"><b>${esc(x.customer_name||'-')}</b><small>${esc(x.service_number||'-')} • ${esc(x.ticket_id||'MANUAL')}<br>${esc(x.address||'Alamat tidak tersedia')}</small><a class="map-btn" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x.address||'')}">▣ MAPS</a><span class="tag">${esc(x.result||'OPEN')}</span></article>`).join('')}</div>`}catch(e){c.innerHTML='<div class="empty-feature">Gagal memuat orderan.</div>'}return}
if(id==='reports'){try{const r=await fetch('/api/web/my-report',{credentials:'same-origin'}).then(x=>x.json());c.innerHTML=`<div class="feature-grid"><div class="feature-card"><span>HARI INI</span><b>${fmt(r.daily??r.summary?.daily??0)}</b></div><div class="feature-card"><span>MINGGU INI</span><b>${fmt(r.weekly??r.summary?.weekly??0)}</b></div><div class="feature-card"><span>TOTAL</span><b>${fmt(r.total??r.all??0)}</b></div></div>`}catch(e){c.innerHTML='<div class="empty-feature">Laporan tidak dapat dimuat.</div>'}return}
if(id==='profile'){try{const m=await fetch('/api/auth/me',{credentials:'same-origin'}).then(x=>x.json());const t=m.technician||{};c.innerHTML=`<div class="feature-card"><div class="profile-row"><span>NAMA</span><b>${esc(t.name||'-')}</b></div><div class="profile-row"><span>NIK</span><b>${esc(t.nik||'-')}</b></div><div class="profile-row"><span>STO</span><b>${esc(t.sto||'-')}</b></div><div class="profile-row"><span>ROLE</span><b>${esc(String(t.role||'-').toUpperCase())}</b></div><div class="profile-row"><span>STATUS</span><b>ACTIVE</b></div></div>`}catch(e){c.innerHTML='<div class="empty-feature">Profil tidak dapat dimuat.</div>'}return}
if(id==='payroll'){c.innerHTML='<div class="empty-feature"><b>PAYROLL MODULE</b><br><br>Modul payroll siap menjadi halaman khusus. Data penghasilan dapat dihubungkan ke rekap order CLOSE, insentif, dan periode payroll tanpa menumpuk di dashboard.</div>';return}
if(id==='techs'){return}}
function fmt(n){return Number(n||0).toLocaleString('id-ID')}
window.KerjaBotMenu={show,showDashboard};
const observer=new MutationObserver(()=>{if(d.classList.contains('hidden'))return});observer.observe(d,{attributes:true,attributeFilter:['class']});
}
const boot=()=>{if($('#dashboard')&&!$('#dashboard').classList.contains('hidden'))shell();else setTimeout(boot,500)};boot();
})();
